Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -30,54 +30,54 @@ jobs:
       run: echo "${{ secrets.MLRUN_PEM }}" > mlrun.pem
     - name: Set permissions on key
       run: chmod 400 mlrun.pem
-#     - name: Install sshpass
-#       run: sudo apt-get install -y sshpass
-#     - name: Copy folder to remote machine
-#       run: |
-#         sshpass ssh -o StrictHostKeyChecking=no -i  mlrun.pem ${{ secrets.USERNAME }}@${{ secrets.IP }} <<EOF
-#         rm -rf /home/ubuntu/ce
-#         EOF
-#         sudo scp -r -o StrictHostKeyChecking=no -i mlrun.pem  /home/runner/work/ce ${{ secrets.USERNAME }}@${{ secrets.IP }}:/home/ubuntu/ce
-#     - name: Cleaning instance
-#       run: |
-#         sshpass ssh -o StrictHostKeyChecking=no -i  mlrun.pem ${{ secrets.USERNAME }}@${{ secrets.IP }} <<EOF
-#         # CLEANUP
-#         echo "helm uninstall mlrun-ce"
-#         helm uninstall -n mlrun mlrun-ce || echo true
-#         echo "helm uninstall monitoring"
-#         helm uninstall -n mlrun monitoring || echo true
-#         echo "delete pv, pvc from mlrun"
-#         kubectl delete all --all -n mlrun
-#         echo "deleting mlrun namepsace";
-#         kubectl delete namespace mlrun || echo true
-#         EOF
+    - name: Install sshpass
+      run: sudo apt-get install -y sshpass
+    - name: Copy folder to remote machine
+      run: |
+        sshpass ssh -o StrictHostKeyChecking=no -i  mlrun.pem ${{ secrets.USERNAME }}@${{ secrets.IP }} <<EOF
+        rm -rf /home/ubuntu/ce
+        EOF
+        sudo scp -r -o StrictHostKeyChecking=no -i mlrun.pem  /home/runner/work/ce ${{ secrets.USERNAME }}@${{ secrets.IP }}:/home/ubuntu/ce
+    - name: Cleaning instance
+      run: |
+        sshpass ssh -o StrictHostKeyChecking=no -i  mlrun.pem ${{ secrets.USERNAME }}@${{ secrets.IP }} <<EOF
+        # CLEANUP
+        echo "helm uninstall mlrun-ce"
+        helm uninstall -n mlrun mlrun-ce || echo true
+        echo "helm uninstall monitoring"
+        helm uninstall -n mlrun monitoring || echo true
+        echo "delete pv, pvc from mlrun"
+        kubectl delete all --all -n mlrun
+        echo "deleting mlrun namepsace";
+        kubectl delete namespace mlrun || echo true
+        EOF
 
-#     - name: CE installation
-#       run: |    
-#         # CE INSTALLATION
-#         sshpass ssh -o StrictHostKeyChecking=no -i  mlrun.pem ${{ secrets.USERNAME }}@${{ secrets.IP }} <<EOF
-#         cd ce/ce/charts/mlrun-ce
-#         echo "helm dependency update"
-#         helm dependency update
-#         echo "create mlrun namepsace"
-#         kubectl create namespace mlrun        
-#         echo "k8s namespaces - $(kubectl get namespace)"
-#         echo "installing community edition"
-#         helm install mlrun-ce --namespace mlrun \
-#         --set minio.resources.requests.memory="128Mi" \
-#         --set  jupyterNotebook.persistence.size="1Gi" \
-#         --set  mlrun.db.persistence.size="1Gi" \
-#         --set  mlrun.api.persistence.size="1Gi" \
-#         --set  mpi-operator.deployment.create="false" \
-#         --set  mlrun.httpDB.dbType="sqlite" \
-#         --set  mlrun.httpDB.dirPath="/mlrun/db" \
-#         --set  mlrun.httpDB.dsn="sqlite:////mlrun/db/mlrun.db?check_same_thread=false"  \
-#         --set  mlrun.httpDB.oldDsn=""  \
-#         --set global.registry.url=${{ secrets.INTERNAL_IP }}:5000  --set global.registry.secretName=""   \
-#         --set global.externalHostAddress=${{ secrets.INTERNAL_IP }}  \
-#         --set nuclio.dashboard.externalIPAddresses[0]=${{ secrets.INTERNAL_IP }}  \
-#         --wait --debug --timeout=1h .
-#         EOF
+    - name: CE installation
+      run: |    
+        # CE INSTALLATION
+        sshpass ssh -o StrictHostKeyChecking=no -i  mlrun.pem ${{ secrets.USERNAME }}@${{ secrets.IP }} <<EOF
+        cd ce/ce/charts/mlrun-ce
+        echo "helm dependency update"
+        helm dependency update
+        echo "create mlrun namepsace"
+        kubectl create namespace mlrun        
+        echo "k8s namespaces - $(kubectl get namespace)"
+        echo "installing community edition"
+        helm install mlrun-ce --namespace mlrun \
+        --set minio.resources.requests.memory="128Mi" \
+        --set  jupyterNotebook.persistence.size="1Gi" \
+        --set  mlrun.db.persistence.size="1Gi" \
+        --set  mlrun.api.persistence.size="1Gi" \
+        --set  mpi-operator.deployment.create="false" \
+        --set  mlrun.httpDB.dbType="sqlite" \
+        --set  mlrun.httpDB.dirPath="/mlrun/db" \
+        --set  mlrun.httpDB.dsn="sqlite:////mlrun/db/mlrun.db?check_same_thread=false"  \
+        --set  mlrun.httpDB.oldDsn=""  \
+        --set global.registry.url=${{ secrets.INTERNAL_IP }}:5000  --set global.registry.secretName=""   \
+        --set global.externalHostAddress=${{ secrets.INTERNAL_IP }}  \
+        --set nuclio.dashboard.externalIPAddresses[0]=${{ secrets.INTERNAL_IP }}  \
+        --wait --debug --timeout=1h .
+        EOF
 
     - name: executing remote ssh commands using password
       uses: appleboy/ssh-action@v0.1.10
